Map musics = {
  0: {
    'filename': "audio/Mrs. GREEN APPLE_Inferno_BPM185_編集済.mp3",
    'name': "Mrs. GREEN APPLE_Inferno_BPM185",
    'artist': "Mrs. GREEN APPLE",
    'BPM': 185.0,
    'feltBPM':185.0,
    'genre1': "j-rock",
    'genre2': 0,
    'danceability': 0,
    'energy': 0,
    'content loudness': 9,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.6,
  },
  1: {
    'filename': "audio/Mrs. GREEN APPLE_WanteD WanteD_BPM160.mp3",
    'name': "Mrs. GREEN APPLE_WanteD WanteD_BPM160",
    'artist': "Mrs. GREEN APPLE",
    'BPM': 160.0,
    'feltBPM':160.0,
    'genre1': "j-rock",
    'genre2': 0,
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.8,
  },
  2: {
    'filename': "audio/Mrs. GREEN APPLE_青と夏__BPM185.mp3",
    'name': "Mrs. GREEN APPLE_青と夏__BPM185",
    'artist': "Mrs. GREEN APPLE",
    'BPM': 185.0,
    'feltBPM':185.0,
    'genre1': "j-rock",
    'genre2': 0,
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.5,
  },
  3: {
    'filename': "audio/WANIMA_アケイン_BPM195.mp3",
    'name': "WANIMA_アゲイン_BPM195",
    'artist': "WANIMA",
    'BPM': 195.0,
    'feltBPM':195.0,
    'genre1': "j-rock",
    'genre2': 0,
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability':0.3,
  },
  4: {
    'filename': "audio/WANIMA_ともに_BPM127.mp3",
    'name': "WANIMA_ともに_BPM127",
    'artist': "WANIMA",
    'BPM': 127.0,
    'feltBPM':127.0,
    'genre1': "j-rock",
    'genre2': 0,
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.6,
  },
  5: {
    'filename': "audio/WANIMA_やってみよう_BPM129.5.mp3",
    'name': "WANIMA_やってみよう_BPM129.5",
    'artist': "WANIMA",
    'BPM': 129.5,
    'feltBPM':129.5,
    'genre1': "j-rock",
    'genre2': 0,
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.6,
  },
  6: {
    'filename': "audio/ステレオカール_おやすみクットナイト_BPM138.mp3",
    'name': "ステレオガール_おやすみグッドナイト_BPM138",
    'artist': "ステレオガール",
    'BPM': 138.0,
    'feltBPM':138.0,
    'genre1': "j-rock",
    'genre2': 0,
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.4,
  },
  7: {
    'filename': "audio/Axol x Alex Skrindo - You [NCS Release]_BPM128.mp3",
    'name': "Axol x Alex Skrindo - You [NCS Release]_BPM128",
    'artist': "Axol x Alex Skrindo",
    'BPM': 128.0,
    'feltBPM':128.0,
    'genre1': "edm",
    'genre2': 0,
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.3,
  },
  8: {
    'filename': "audio/Calling You (Club Edit)_BPM128.mp3",
    'name': "Calling You (Club Edit)_BPM128",
    'artist': "Stephan F",
    'BPM': 128.0,
    'feltBPM':128.0,
    'genre1': "edm",
    'genre2': 0,
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.4,
  },
  9: {
    'filename': "audio/Higher (Original Mix)_BPM128.mp3",
    'name': "Higher (Original Mix)_BPM128",
    'artist': "Tubotoronic",
    'BPM': 128.0,
    'feltBPM':128.0,
    'genre1': "edm",
    'genre2': 0,
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.4,
  },
  10: {
    'filename': "audio/Fujii Kaze - Kirari_BPM117.mp3",
    'name': "Fujii Kaze - Kirari_BPM117",
    'artist': "Fujii Kaze",
    'BPM': 117.0,
    'feltBPM':117.0,
    'genre1': "j-groovy",
    'genre2': "j-pop",
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.3,
  },
  11: {
    'filename': "audio/King Gnu_BOY_BPM110_編集済.mp3",
    'name': "King Gnu - BOY_BPM110",
    'artist': "King Gnu",
    'BPM': 110.0,
    'feltBPM':110.0,
    'genre1': "j-pop",
    'genre2': 0,
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.2,
  },
  12: {
    'filename': "audio/サカナクション_ミューシック_BPM136_編集済.mp3",
    'name': "サカナクション_ミュージック_BPM136",
    'artist': "サカナクション",
    'BPM': 136.0,
    'feltBPM':136.0,
    'genre1': "techno",
    'genre2': "j-pop",
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.2,
  },
  13: {
    'filename': "audio/Vaundy_踊り子_BPM157_編集済.mp3", 
    'name': "踊り子_BPM157",
    'artist': "Vaundy",
    'BPM': 157.0,
    'feltBPM': 157.0,
    'genre1': "j-pop",
    'genre2': "j-groovy",
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.3,
  },
  14: {
    'filename': "audio/(IZONE)Panorama ZONE_BPM126.mp3",
    'name': "아이즈원 (IZONE)Panorama ZONE_BPM126",
    'artist': "아이즈원 (IZONE)Panorama",
    'BPM': 126.0,
    'feltBPM':126.0,
    'genre1': "k-pop",
    'genre2': 0,
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.2,
  },
  15: {
    'filename': "audio/Mela緑黄色社会_BPM138.mp3",
    'name': "Mela緑黄色社会_BPM138",
    'artist': "緑黄色社会",
    'BPM': 138.0,
    'feltBPM':138.0,
    'genre1': "j-rock",
    'genre2': "j-pop",
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.5,
  },
  16: {
    'filename': "audio/YOASOBI  三原色_BPM128.mp3",
    'name': "YOASOBI  三原色_BPM128",
    'artist': "YOASOBI",
    'BPM': 128.0,
    'feltBPM':128.0,
    'genre1': "j-pop",
    'genre2': 0,
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0,
  },
  17: {
    'filename':"audio/BLACKPINK(AS IF ITS YOUR LAST)BPM125.mp3",
    'name': "BLACKPINK - 마지막처럼 (AS IF ITS YOUR LAST)BPM125",
    'artist': "BLACKPINK",
    'BPM': 125.0,
    'feltBPM':125.0,
    'genre1': "k-pop",
    'genre2': 0,
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.3,
  },
  18: {
    'filename': "audio/showmore - 1mmOfficial Lyric Video_BPM93.mp3",
    'name': "showmore - 1mmOfficial Lyric Video_BPM93",
    'artist': "1mmOfficial",
    'BPM': 93.0,
    'feltBPM':93.0,
    'genre1': "j-groovy",
    'genre2': "j-pop",
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.7,
  },
  19: {
    'filename': "audio/Naked Men 見ろ裸の俺たちを_BPM127.mp3",
    'name': "Naked Men 見ろ裸の俺たちを_BPM127",
    'artist': "デーモン閣下",
    'BPM': 127.0,
    'feltBPM':127.0,
    'genre1': "j-pop",
    'genre2': "ethnic",
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.5,
  },
  20: {
    'filename': "audio/サンフラサ中野くん_Runner_BPM124.mp3",
    'name': "サンプラザ中野くん_Runner_BPM124",
    'artist': "サンプラザ中野くん",
    'BPM': 124.0,
    'feltBPM':248.0,
    'genre1': "j-rock",
    'genre2': 0,
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.7,
  },
  21: {
    'filename': "audio/Despacito_BPM150.mp3",
    'name': "Despacito_BPM150",
    'artist': "Luis Fonsi",
    'BPM': 150.0,
    'feltBPM':150.0,
    'genre1': "edm",
    'genre2': "ethnic",
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.3,
  },
  22: {
    'filename': "audio/Shape of You_BPM150.mp3",
    'name': "Shape of You_BPM150",
    'artist': "Ed Sheeran",
    'BPM': 150.0,
    'feltBPM':150.0,
    'genre1': "techno",
    'genre2': "w-pop",
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.8,
  },
  23: {
    'filename': "audio/[Official Music Video] Perfume「レーサーヒーム」-K54CYowOqxM.mp3",
    'name': "レーザービーム_BPM135",
    'artist': "Perfume",
    'BPM': 135.008,
    'feltBPM':135.008,
    'genre1': "techno",
    'genre2': "j-pop",
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.7,
  },
  24: {
    'filename': "audio/【CHUNITHM AIR 音源】Philosopher _ 少女病-9y-T1DuNuSY.mp3",
    'name': "少女病_BPM145",
    'artist': "Philosopher",
    'BPM': 145.064,
    'feltBPM':145.064,
    'genre1': "j-rock",
    'genre2': 0,
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.3,
  },
  25: {
    'filename': "audio/9mm Parabellum Bullet - インフェルノ-8DizBlRFMD4.mp3",
    'name': "インフェルノ_BPM195",
    'artist': "9mm Parabellum Bullet",
    'BPM': 195.042,
    'feltBPM':195.042,
    'genre1': "j-rock",
    'genre2': 0,
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.3,
  },
  26: {
    'filename': "audio/9mm Parabellum Bullet - サクリファイス-CVNy1p3CrVM.mp3",
    'name': "サクリファイス_BPM200",
    'artist': "9mm Parabellum Bullet",
    'BPM': 199.978,
    'feltBPM':199.978,
    'genre1': "j-rock",
    'genre2': 0,
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.5,
  },
  27: {
    'filename': "audio/Atarashii Hikari-uCrhhsOPav4.mp3",
    'name': "Atarashii Hikari_BPM180",
    'artist': "9mm Parabellum Bullet",
    'BPM': 179.879,
    'feltBPM':179.879,
    'genre1': "j-rock",
    'genre2': "alternative/indies",
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.2,
  },
  28: {
    'filename': "audio/Black Market Blues-rJp9A-f5nR0.mp3",
    'name': "Black Market_BPM158",
    'artist': "9mm Parabellum Bullet",
    'BPM': 157.955,
    'feltBPM':157.955,
    'genre1': "j-rock",
    'genre2': "alternative/indies",
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.6,
  },
  29: {
    'filename': "audio/KANA-BOON 『フルトライフ』Music Video-adK2Fol2SkM.mp3",
    'name': "フルドライブ_BPM178",
    'artist': "KANA-BOON",
    'BPM': 177.965,
    'feltBPM':177.965,
    'genre1': "j-rock",
    'genre2': 0,
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.7,
  },
  30: {
    'filename': "audio/MAN WITH A MISSION 『Raise your flag』-PiQpGzYMVos.mp3",
    'name': "Raise your flag_BPM145",
    'artist': "MAN WITH A MISSION",
    'BPM': 144.946,
    'feltBPM':144.946,
    'genre1': "alternative/indies",
    'genre2': "metal",
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.6,
  },
  31: {
    'filename': "audio/THE BACK HORN｢コハルトフルー｣MUSIC VIDEO-yf_xwI865gg.mp3",
    'name': "コバルトブルー_BPM114",
    'artist': "THE BACK HORN",
    'BPM': 113.628,
    'feltBPM':113.628,
    'genre1': "j-rock",
    'genre2': "alternative/indies",
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.6,
  },
  32: {
    'filename': "audio/THE BACK HORN｢戦う君よ｣MUSIC VIDEO-QPdhZR_CIck.mp3",
    'name': "戦う君よ_BPM110",
    'artist': "THE BACK HORN",
    'BPM': 109.558,
    'feltBPM':109.558,
    'genre1': "j-rock",
    'genre2': "alternative/indies",
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.5,
  },
  33: {
    'filename': "audio/THE BACK HORN｢罠｣MUSIC VIDEO-_aw01by-hzE.mp3",
    'name': "罠_BPM198",
    'artist': "THE BACK HORN",
    'BPM': 198.047,
    'feltBPM':198.047,
    'genre1': "j-rock",
    'genre2': "alternative/indies",
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.4,
  },
  34: {
    'filename': "audio/フレテリック「オンリーワンター」MusicVideo _ frederic“ONLYWONDER”-oCrwzN6eb4Q.mp3",
    'name': "オンリーワンター_BPM167",
    'artist': "フレデリック",
    'BPM': 166.662,
    'feltBPM':166.662,
    'genre1': "techno",
    'genre2': "j-pop",
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.6,
  },
  35: {
    'filename': "audio/マチカミ少女-qTrPVe3GZys.mp3",
    'name': "マチガミ少女_BPM99",
    'artist': "仲恵光城",
    'BPM': 98.512,
    'feltBPM':98.512,
    'genre1': "j-rock",
    'genre2': 0,
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.3,
  },
  36: {
    'filename': "audio/刃-x_FIQdFnqo8.mp3",
    'name': "刃_BPM151",
    'artist': "THE BACK HORN",
    'BPM': 151.001,
    'feltBPM':151.001,
    'genre1': "j-rock",
    'genre2': "alternative/indies",
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.4,
  },
  37: {
    'filename': "audio/Vaundy_怪獣の花唄_BPM150_編集済.mp3",
    'name': "怪獣の花唄_BPM150",
    'artist': "Vaundy",
    'BPM': 150.0,
    'feltBPM': 150.0,
    'genre1': "j-pop",
    'genre2': 0,
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.5,
  },
  38: {
    'filename': "audio/Vaundy_不可幸力_BPM94.mp3",
    'name': "不可幸力_BPM94",
    'artist': "Vaundy",
    'BPM': 94.0,
    'feltBPM': 94.0,
    'genre1': "j-pop",
    'genre2': "r&b/soul",
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.2,
  },
  39: {
    'filename': "audio/Vaundy_東京フラッシュ_BPM98.mp3",
    'name': "東京フラッシュ_BPM98",
    'artist': "Vaundy",
    'BPM': 98.0,
    'feltBPM': 98.0,
    'genre1': "j-pop",
    'genre2': "alternative/indies",
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.7,
  },
  40: {
    'filename': "audio/Vaundy_恋風邪にのせて_BPM118_編集済.mp3",
    'name': "恋風邪にのせて_BPM118",
    'artist': "Vaundy",
    'BPM': 118.0,
    'feltBPM': 118.0,
    'genre1': "j-pop",
    'genre2': 0,
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.5,
  },
  41: {
    'filename': "audio/Vaundy_花占い_BPM135_編集済.mp3",
    'name': "花占い_BPM135",
    'artist': "Vaundy",
    'BPM': 135.0,
    'feltBPM': 135.0,
    'genre1': "j-pop",
    'genre2': 0,
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.4,
  },
  42: {
    'filename': "audio/なとり_Overdose_BPM118_編集済.mp3.mp3",
    'name': "Overdose_BPM118",
    'artist': "なとり",
    'BPM': 118.0,
    'feltBPM': 118.0,
    'genre1': "j-pop",
    'genre2': "r&b/soul",
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.7,
  },
  43: {
    'filename': "audio/緑黄色社会_キャラクター_BPM124_編集済.mp3",
    'name': "キャラクター_BPM124",
    'artist': "緑黄色社会",
    'BPM': 124.0,
    'feltBPM': 124.0,
    'genre1': "j-pop",
    'genre2': 0,
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.7,
  },
  44: {
    'filename': "audio/緑黄色社会_陽はまた昇るから_BPM142_編集済.mp3",
    'name': "陽はまた昇るから_BPM142",
    'artist': "緑黄色社会",
    'BPM': 142.0,
    'feltBPM': 142.0,
    'genre1': "j-pop",
    'genre2': 0,
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.5,
  },
  45: {
    'filename': "audio/Doja Cat - Say So_BPM111.mp3",
    'name': "Say So_BPM111",
    'artist': "Doja Cat",
    'BPM': 111.0,
    'feltBPM': 111.0,
    'genre1': "r&b/soul",
    'genre2': "hip-hop/pop-rap",
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.9,
  },
  46: {
    'filename': "audio/Doja Cat - Boss Bitch (Lyrics).mp3",
    'name': "Boss Bitch_BPM126",
    'artist': "Doja Cat",
    'BPM': 126.0,
    'feltBPM': 126.0,
    'genre1': "hip-hop/pop-rap",
    'genre2': "edm",
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.7,
  },
  47: {
    'filename': "audio/Doja Cat_Like That (feat. Gucci Mane)_BPM106.mp3",
    'name': "Like That (feat. Gucci Mane)_BPM106",
    'artist': "Doja Cat",
    'BPM': 106.0,
    'feltBPM': 106.0,
    'genre1': "r&b/soul",
    'genre2': "hip-hop/pop-rap",
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.5,
  },
  48: {
    'filename': "audio/The Kid LAROI, Justin Bieber - Stay_BPM170.mp3",
    'name': "STAY_BPM170",
    'artist': "The Kid LAROI, Justin Bieber",
    'BPM': 170.0,
    'feltBPM': 170.0,
    'genre1': "w-pop",
    'genre2': "hip-hop/pop-rap",
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.9,
  },
  49: {
    'filename': "audio/JustinBieberWhatDoYouMeanBPM125.mp3",
    'name': "What Do You Mean?_BPM125",
    'artist': "Justin Bieber",
    'BPM': 125.0,
    'feltBPM': 125.0,
    'genre1': "w-pop",
    'genre2': 0,
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.3,
  },
  50: {
    'filename': "audio/Justin Bieber_Baby ft. Ludacris_BPM130.mp3",
    'name': "Baby ft. Ludacris_BPM130",
    'artist': "Justin Bieber",
    'BPM': 130.0,
    'feltBPM': 130.0,
    'genre1': "w-pop",
    'genre2': "hip-hop/pop-rap",
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.4,
  },
  51: {
    'filename': "audio/Mark Ronson _Uptown Funk (feat. Bruno Mars)_BPM115.mp3",
    'name': "Uptown Funk (feat. Bruno Mars)_BPM115",
    'artist': "Mark Ronson ",
    'BPM': 115.0,
    'feltBPM': 115.0,
    'genre1': "funk",
    'genre2': "w-pop",
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.9,
  },
  52: {
    'filename': "audio/Official髭男dism_ミックスナッツ_BPM150_編集済.mp3",
    'name': "ミックスナッツ_BPM150",
    'artist': "Official髭男dism",
    'BPM': 150.0,
    'feltBPM': 150.0,
    'genre1': "j-pop",
    'genre2': 0,
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.4,
  },
  53: {
    'filename': "audio/Official髭男dism_Pretender_BPM92.mp3",
    'name': "Pretender_BPM92",
    'artist': "Official髭男dism",
    'BPM': 92.0,
    'feltBPM': 92.0,
    'genre1': "j-pop",
    'genre2': "j-rock",
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.1,
  },
  54: {
    'filename': "audio/Official髭男dism_Cry Baby_BPM100.mp3",
    'name': "Cry Baby_BPM100",
    'artist': "Official髭男dism",
    'BPM': 100.0,
    'feltBPM': 100.0,
    'genre1': "alternative/indies",
    'genre2': "j-pop",
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.4,
  },
  55: {
    'filename': "audio/Official髭男dism_ノータウト_BPM150.mp3",
    'name': "ノーダウト_BPM150",
    'artist': "Official髭男dism",
    'BPM': 150.0,
    'feltBPM': 150.0,
    'genre1': "r&b/soul",
    'genre2': "j-pop",
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.4,
  },
  56: {
    'filename': "audio/Official髭男dism_宿命_BPM82.mp3",
    'name': "宿命_BPM82",
    'artist': "Official髭男dism",
    'BPM': 82.0,
    'feltBPM': 82.0,
    'genre1': "j-pop",
    'genre2': "r&b/soul",
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.1,
  },
  57: {
    'filename': "audio/Official髭男dism_イエスタテイ_BPM130.mp3",
    'name': "イエスタデイ_BPM130",
    'artist': "Official髭男dism",
    'BPM': 130.0,
    'feltBPM': 130.0,
    'genre1': "j-pop",
    'genre2': 0,
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.6,
  },
  58: {
    'filename': "audio/Official髭男dism_FIRE GROUND_BPM114.mp3",
    'name': "FIRE GROUND_BPM114",
    'artist': "Official髭男dism",
    'BPM': 114.0,
    'feltBPM': 114.0,
    'genre1': "alternative/indies",
    'genre2': "r&b/soul",
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.8,
  },
  59: {
    'filename': "audio/Official髭男dism_Stand By You_BPM154.mp3",
    'name': "Stand By You_BPM154",
    'artist': "Official髭男dism",
    'BPM': 154.0,
    'feltBPM': 154.0,
    'genre1': "r&b/soul",
    'genre2': "j-pop",
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.5,
  },
  60: {
    'filename': "audio/Official髭男dism_115万キロのフィルム_BPM97.mp3",
    'name': "115万キロのフィルム_BPM97",
    'artist': "Official髭男dism",
    'BPM': 97.0,
    'feltBPM': 97.0,
    'genre1': "j-pop",
    'genre2': 0,
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.6,
  },
  61: {
    'filename': "audio/YOASOBI_怪物_BPM170_編集済.mp3",
    'name': "怪物_BPM170",
    'artist': "YOASOBI",
    'BPM': 170.0,
    'feltBPM': 170.0,
    'genre1': "j-pop",
    'genre2': "vocaloid",
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.6,
  },
  62: {
    'filename': "audio/YOASOBI_三原色_BPM128_編集済.mp3",
    'name': "三原色_BPM128",
    'artist': "YOASOBI",
    'BPM': 128.0,
    'feltBPM': 128.0,
    'genre1': "j-pop",
    'genre2': 0,
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.9,
  },
  63: {
    'filename': "audio/YOASOBI_群青_BPM135_編集済.mp3",
    'name': "群青_BPM135",
    'artist': "YOASOBI",
    'BPM': 135.0,
    'feltBPM': 135.0,
    'genre1': "j-pop",
    'genre2': 0,
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.9,
  },
  64: {
    'filename': "audio/YOASOBI_ハルシオン_BPM130_編集済.mp3",
    'name': "ハルジオン_BPM130",
    'artist': "YOASOBI",
    'BPM': 130.0,
    'feltBPM': 130.0,
    'genre1': "j-pop",
    'genre2': 0,
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.6,
  },
  65: {
    'filename': "audio/YOASOBI_あの夢をなそって_BPM180.mp3",
    'name': "あの夢をなぞって_BPM180",
    'artist': "YOASOBI",
    'BPM': 180.0,
    'feltBPM': 180.0,
    'genre1': "j-pop",
    'genre2': 0,
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.4,
  },
  66: {
    'filename': "audio/YOASOBI_祝福_BPM170_編集済.mp3",
    'name': "祝福_BPM170",
    'artist': "YOASOBI",
    'BPM': 170.0,
    'feltBPM': 170.0,
    'genre1': "j-pop",
    'genre2': 0,
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.8,
  },
  67: {
    'filename': "audio/YOASOBI_夜に駆ける_BPM130_編集済.mp3",
    'name': "夜に駆ける_BPM130",
    'artist': "YOASOBI",
    'BPM': 130.0,
    'feltBPM': 130.0,
    'genre1': "j-pop",
    'genre2': 0,
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.4,
  },
  68: {
    'filename': "audio/Ayase_シネマ feat.初音ミク_BPM124.mp3",
    'name': "シネマ feat.初音ミク_BPM124",
    'artist': "Ayase",
    'BPM': 124.0,
    'feltBPM': 124.0,
    'genre1': "vocaloid",
    'genre2': 0,
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.6,
  },
  69: {
    'filename': "audio/Eve_廻廻奇譚_BPM185.mp3",
    'name': "廻廻奇譚_BPM185",
    'artist': "Eve",
    'BPM': 185.0,
    'feltBPM': 185.0,
    'genre1': "alternative/indies",
    'genre2': "hip-hop/pop-rap",
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.5,
  },
  70: {
    'filename': "audio/ASIAN KUNG-FU GENERATION _リライト(2016ver.)_BPM179.mp3",
    'name': "リライト(2016ver.)_BPM179",
    'artist': "ASIAN KUNG-FU GENERATION ",
    'BPM': 179.0,
    'feltBPM': 179.0,
    'genre1': "j-rock",
    'genre2': 0,
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.5,
  },
  71: {
    'filename': "audio/SHISHAMO_明日も_BPM179.mp3",
    'name': "明日も_BPM179",
    'artist': "SHISHAMO",
    'BPM': 179.0,
    'feltBPM': 179.0,
    'genre1': "j-rock",
    'genre2': "j-pop",
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.5,
  },
  72: {
    'filename': "audio/RADWIMPS_前前前世_BPM190.mp3",
    'name': "前前前世_BPM190",
    'artist': "RADWIMPS",
    'BPM': 190.0,
    'feltBPM': 190.0,
    'genre1': "j-rock",
    'genre2': 0,
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.5,
  },
  73: {
    'filename': "audio/Taylor Swift_Shake It Off_BPM160.mp3",
    'name': "Shake It Off_BPM160",
    'artist': "Taylor Swift",
    'BPM': 160.0,
    'feltBPM': 160.0,
    'genre1': "w-pop",
    'genre2': 0,
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.7,
  },
  74: {
    'filename': "audio/椎名林檎_NIPPON_BPM173.mp3",
    'name': "NIPPON_BPM173",
    'artist': "椎名林檎",
    'BPM': 173.0,
    'feltBPM': 173.0,
    'genre1': "j-pop",
    'genre2': 0,
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.5,
  },
  75: {
    'filename': "audio/スキマスイッチ_全力少年_BPM134.mp3",
    'name': "全力少年_BPM134",
    'artist': "スキマスイッチ",
    'BPM': 134.0,
    'feltBPM': 134.0,
    'genre1': "j-pop",
    'genre2': 0,
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.5,
  },
  76: {
    'filename': "audio/サカナクション_新宝島_BPM158_編集済.mp3",
    'name': "新宝島_BPM158",
    'artist': "サカナクション",
    'BPM': 158.0,
    'feltBPM': 158.0,
    'genre1': "j-pop",
    'genre2': "alternative/indies",
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.4,
  },
  77: {
    'filename': "audio/TheFatRat_Xenogenesis_BPM145.mp3",
    'name': "TheFatRat_Xenogenesis_BPM145",
    'artist': "TheFatRat",
    'BPM': 145.0,
    'feltBPM': 145.0,
    'genre1': "edm",
    'genre2': "",
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.5,
  },
  78: {
    'filename': "audio/TheFatRat_Ascendancy_BPM167.mp3",
    'name': "TheFatRat_Ascendancy_BPM167",
    'artist': "TheFatRat",
    'BPM': 167.0,
    'feltBPM': 167.0,
    'genre1': "edm",
    'genre2': "",
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.5,
  },
  79: {
    'filename': "audio/TheFatRat_Time Lapse_BPM127.mp3",
    'name': "TheFatRat_Time Lapse_BPM127",
    'artist': "TheFatRat",
    'BPM': 127.0,
    'feltBPM': 127.0,
    'genre1': "edm",
    'genre2': "",
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.5,
  },
  80: {
    'filename': "audio/TheFatRat_Monody (feat. Laura Brehm)_BPM160.mp3",
    'name': "TheFatRat_Monody (feat. Laura Brehm)_BPM160",
    'artist': "TheFatRat",
    'BPM': 160.0,
    'feltBPM': 160.0,
    'genre1': "edm",
    'genre2': "",
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.5,
  },
  81: {
    'filename': "audio/TheFatRat_Stronger_BPM160.mp3",
    'name': "TheFatRat_Stronger_BPM160",
    'artist': "TheFatRat",
    'BPM': 160.0,
    'feltBPM': 160.0,
    'genre1': "edm",
    'genre2': "",
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.5,
  },
  82: {
    'filename': "audio/TheFatRat_Let Love Win_BPM148.mp3",
    'name': "TheFatRat_Let Love Win_BPM148",
    'artist': "TheFatRat",
    'BPM': 148.0,
    'feltBPM': 148.0,
    'genre1': "edm",
    'genre2': "",
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.5,
  },
  83: {
    'filename': "audio/TheFatRat_Kingdom Come_BPM172.mp3",
    'name': "TheFatRat_Kingdom Come_BPM172",
    'artist': "TheFatRat",
    'BPM': 172.0,
    'feltBPM': 172.0,
    'genre1': "edm",
    'genre2': "",
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.5,
  },
  84: {
    'filename': "audio/いきものがかり_じょいふる_BPM159_編集済.mp3",
    'name': "いきものがかり_じょいふる_BPM159",
    'artist': "いきものがかり",
    'BPM': 159.0,
    'feltBPM': 159.0,
    'genre1': "j-pop",
    'genre2': "j-rock",
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.8,
  },
  85: {
    'filename': "audio/Ado_うっせぇわ_BPM178.mp3",
    'name': "Ado_うっせぇわ_BPM178",
    'artist': "Ado",
    'BPM': 178,
    'feltBPM': 178,
    'genre1': "j-pop",
    'genre2': "r&b/soul",
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.5,
  },
  86: {
    'filename': "audio/Ado_阿修羅ちゃん_BPM156.mp3",
    'name': "Ado_阿修羅ちゃん_BPM156",
    'artist': "Ado",
    'BPM': 156.0,
    'feltBPM': 156.0,
    'genre1': "j-pop",
    'genre2': "vocaloid",
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.7,
  },
  87: {
    'filename': "audio/Neru_ロストワンの号哭_BPM162_編集済.mp3",
    'name': "Neru_ロストワンの号哭_BPM162",
    'artist': "Neru",
    'BPM': 162.0,
    'feltBPM': 162.0,
    'genre1': "vocaloid",
    'genre2': "",
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.8,
  },
  88: {
    'filename': "audio/Neru_脱法ロック_BPM155.mp3",
    'name': "Neru_脱法ロック_BPM155",
    'artist': "Neru",
    'BPM': 155.0,
    'feltBPM': 155.0,
    'genre1': "vocaloid",
    'genre2': "",
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.6,
  },
  89: {
    'filename': "audio/じーざすP_リモコン_BPM162.mp3",
    'name': "じーざすP_リモコン_BPM162",
    'artist': "じーざすP",
    'BPM': 162.0,
    'feltBPM': 162.0,
    'genre1': "vocaloid",
    'genre2': "",
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.5,
  },
  90: {
    'filename': "audio/HoneyWorks_イノコリ先生_BPM165.mp3",
    'name': "HoneyWorks_イノコリ先生_BPM165",
    'artist': "HoneyWorks",
    'BPM': 165.0,
    'feltBPM': 165.0,
    'genre1': "vocaloid",
    'genre2': "",
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.5,
  },
  91: {
    'filename': "audio/Creepy Nuts_2way nice guy_BPM130.mp3",
    'name': "Creepy Nuts_2way nice guy_BPM130",
    'artist': "Creepy Nuts",
    'BPM': 130.0,
    'feltBPM': 130.0,
    'genre1': "hip-hop/pop-rap",
    'genre2': "j-pop",
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.7,
  },
  92: {
    'filename': "audio/Creepy Nuts_よふかしのうた_BPM115_編集済.mp3",
    'name': "Creepy Nuts_よふかしのうた_BPM115",
    'artist': "Creepy Nuts",
    'BPM': 115.0,
    'feltBPM': 115.0,
    'genre1': "hip-hop/pop-rap",
    'genre2': "j-pop",
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.4,
  },
  93: {
    'filename': "audio/Creepy Nuts_Bad Orangez_BPM180.mp3",
    'name': "Creepy Nuts_Bad Orangez_BPM180",
    'artist': "Creepy Nuts",
    'BPM': 180.0,
    'feltBPM': 180.0,
    'genre1': "hip-hop/pop-rap",
    'genre2': "j-pop",
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.5,
  },
  94: {
    'filename': "audio/Stray Kids_God's Menu_BPM157.mp3",
    'name': "Stray Kids_God's Menu_BPM157",
    'artist': "Stray Kids",
    'BPM': 157.0,
    'feltBPM': 157.0,
    'genre1': "k-pop",
    'genre2': "edm",
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.5,
  },
  95: {
    'filename': "audio/Stray Kids_CASE 143_BPM100.mp3",
    'name': "Stray Kids_CASE 143_BPM100",
    'artist': "Stray Kids",
    'BPM': 100.0,
    'feltBPM': 100.0,
    'genre1': "k-pop",
    'genre2': "edm",
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.5,
  },
  96: {
    'filename': "audio/Stray Kids_FREEZE_BPM160.mp3",
    'name': "Stray Kids_FREEZE_BPM160",
    'artist': "Stray Kids",
    'BPM': 160.0,
    'feltBPM': 160.0,
    'genre1': "k-pop",
    'genre2': "edm",
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.6,
  },
  97: {
    'filename': "audio/BTS_I NEED U_BPM158.mp3",
    'name': "BTS_I NEED U_BPM158",
    'artist': "BTS",
    'BPM': 158.0,
    'feltBPM': 158.0,
    'genre1': "k-pop",
    'genre2': "",
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.5,
  },
  98: {
    'filename': "audio/ENHYPEN_Tamed-Dashed_BPM155.mp3",
    'name': "ENHYPEN_Tamed-Dashed_BPM155",
    'artist': "ENHYPEN",
    'BPM': 155.0,
    'feltBPM': 155.0,
    'genre1': "k-pop",
    'genre2': "",
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0,
    'beatability': 0.5,
  },
  

 
};