import 'package:flutter/material.dart';
Map musics = {
  0: {
    'filename': "audio/Mrs. GREEN APPLE_Inferno_BPM185.mp3",
    'name': "Mrs. GREEN APPLE_Inferno_BPM185",
    'artist': "Mrs. GREEN APPLE",
    'BPM': 185.0,
    'feltBPM':185.0,
    'genre1': "j-rock",
    'genre2': 0,
    'danceability': 0,
    'energy': 0,
    'content loudness': 9,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0
  },
  1: {
    'filename': "audio/Mrs. GREEN APPLE_WanteD WanteD_BPM160.mp3",
    'name': "Mrs. GREEN APPLE_WanteD WanteD_BPM160",
    'artist': "Mrs. GREEN APPLE",
    'BPM': 160.0,
    'feltBPM':160.0,
    'genre1': "j-rock",
    'genre2': 0,
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0
  },
  2: {
    'filename': "audio/Mrs. GREEN APPLE_青と夏__BPM185.mp3",
    'name': "Mrs. GREEN APPLE_青と夏__BPM185",
    'artist': "Mrs. GREEN APPLE",
    'BPM': 185.0,
    'feltBPM':185.0,
    'genre1': "j-rock",
    'genre2': 0,
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0
  },
  3: {
    'filename': "audio/WANIMA_アケイン_BPM195.mp3",
    'name': "WANIMA_アゲイン_BPM195",
    'artist': "WANIMA",
    'BPM': 195.0,
    'feltBPM':195.0,
    'genre1': "j-rock",
    'genre2': 0,
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0
  },
  4: {
    'filename': "audio/WANIMA_ともに_BPM127.mp3",
    'name': "WANIMA_ともに_BPM127",
    'artist': "WANIMA",
    'BPM': 127.0,
    'feltBPM':127.0,
    'genre1': "j-rock",
    'genre2': 0,
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0
  },
  5: {
    'filename': "audio/WANIMA_やってみよう_BPM129.5.mp3",
    'name': "WANIMA_やってみよう_BPM129.5",
    'artist': "WANIMA",
    'BPM': 129.5,
    'feltBPM':129.5,
    'genre1': "j-rock",
    'genre2': 0,
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0
  },
  6: {
    'filename': "audio/ステレオカール_おやすみクットナイト_BPM138.mp3",
    'name': "ステレオガール_おやすみグッドナイト_BPM138",
    'artist': "ステレオガール",
    'BPM': 138.0,
    'feltBPM':138.0,
    'genre1': "j-rock",
    'genre2': 0,
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0
  },
  7: {
    'filename': "audio/Axol x Alex Skrindo - You [NCS Release]_BPM128.mp3",
    'name': "Axol x Alex Skrindo - You [NCS Release]_BPM128",
    'artist': "Axol x Alex Skrindo",
    'BPM': 128.0,
    'feltBPM':128.0,
    'genre1': "EDM",
    'genre2': 0,
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0
  },
  8: {
    'filename': "audio/Calling You (Club Edit)_BPM128.mp3",
    'name': "Calling You (Club Edit)_BPM128",
    'artist': "Stephan F",
    'BPM': 128.0,
    'feltBPM':128.0,
    'genre1': "EDM",
    'genre2': 0,
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0
  },
  9: {
    'filename': "audio/Higher (Original Mix)_BPM128.mp3",
    'name': "Higher (Original Mix)_BPM128",
    'artist': "Tubotoronic",
    'BPM': 128.0,
    'feltBPM':128.0,
    'genre1': "EDM",
    'genre2': 0,
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0
  },
  10: {
    'filename': "audio/Fujii Kaze - Kirari_BPM117.mp3",
    'name': "Fujii Kaze - Kirari_BPM117",
    'artist': "Fujii Kaze",
    'BPM': 117.0,
    'feltBPM':117.0,
    'genre1': "j-groovy",
    'genre2': "j-pop",
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0
  },
  11: {
    'filename': "audio/King Gnu - BOY_BPM110.mp3",
    'name': "King Gnu - BOY_BPM110",
    'artist': "King Gnu",
    'BPM': 110.0,
    'feltBPM':110.0,
    'genre1': "j-pop",
    'genre2': 0,
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0
  },
  12: {
    'filename': "audio/サカナクション  ミューシック_BPM136.mp3",
    'name': "サカナクション  ミュージック_BPM136",
    'artist': "サカナクション",
    'BPM': 136.0,
    'feltBPM':136.0,
    'genre1': "techno",
    'genre2': "j-pop",
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0
  },
  13: {
    'filename': "audio/踊り子_BPM157.mp3", 
    'name': "踊り子_BPM157",
    'artist': "Vaundy",
    'BPM': 157.0,
    'feltBPM': 157.0,
    'genre1': "j-pop",
    'genre2': "j-groovy",
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0
  },
  14: {
    'filename': "audio/아이즈원 (IZONE)Panorama ZONE_BPM126.mp3",
    'name': "아이즈원 (IZONE)Panorama ZONE_BPM126",
    'artist': "아이즈원 (IZONE)Panorama",
    'BPM': 126.0,
    'feltBPM':126.0,
    'genre1': "k-pop",
    'genre2': 0,
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0
  },
  15: {
    'filename': "audio/Mela緑黄色社会_BPM138.mp3",
    'name': "Mela緑黄色社会_BPM138",
    'artist': "緑黄色社会",
    'BPM': 138.0,
    'feltBPM':138.0,
    'genre1': "j-rock",
    'genre2': "j-pop",
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0
  },
  16: {
    'filename': "audio/YOASOBI  三原色_BPM128.mp3",
    'name': "YOASOBI  三原色_BPM128",
    'artist': "YOASOBI",
    'BPM': 128.0,
    'feltBPM':128.0,
    'genre1': "j-pop",
    'genre2': 0,
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0
  },
  17: {
    'filename':"audio/BLACKPINK - 마지막처럼 (AS IF ITS YOUR LAST)BPM125.mp3",
    'name': "BLACKPINK - 마지막처럼 (AS IF ITS YOUR LAST)BPM125",
    'artist': "BLACKPINK",
    'BPM': 125.0,
    'feltBPM':125.0,
    'genre1': "k-pop",
    'genre2': 0,
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0
  },
  18: {
    'filename': "audio/showmore - 1mmOfficial Lyric Video_BPM93.mp3",
    'name': "showmore - 1mmOfficial Lyric Video_BPM93",
    'artist': "1mmOfficial",
    'BPM': 93.0,
    'feltBPM':93.0,
    'genre1': "j-groovy",
    'genre2': "j-pop",
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0
  },
  19: {
    'filename': "audio/Naked Men 見ろ裸の俺たちを_BPM127.mp3",
    'name': "Naked Men 見ろ裸の俺たちを_BPM127",
    'artist': "デーモン閣下",
    'BPM': 127.0,
    'feltBPM':127.0,
    'genre1': "j-pop",
    'genre2': "ethnic",
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0
  },
  20: {
    'filename': "audio/サンフラサ中野くん_Runner_BPM124.mp3",
    'name': "サンプラザ中野くん_Runner_BPM124",
    'artist': "サンプラザ中野くん",
    'BPM': 124.0,
    'feltBPM':248.0,
    'genre1': "j-rock",
    'genre2': 0,
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0
  },
  21: {
    'filename': "audio/Despacito_BPM150.mp3",
    'name': "Despacito_BPM150",
    'artist': "Luis Fonsi",
    'BPM': 150.0,
    'feltBPM':150.0,
    'genre1': "EDM",
    'genre2': "ethnic",
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0
  },
  22: {
    'filename': "audio/Shape of You_BPM150.mp3",
    'name': "Shape of You_BPM150",
    'artist': "Ed Sheeran",
    'BPM': 150.0,
    'feltBPM':150.0,
    'genre1': "techno",
    'genre2': "western",
    'danceability': 0,
    'energy': 0,
    'content loudness': 0,
    'shuffle': 0,
    'waltz': 0,
    'bpmHalf': 0,
    'bpmNotHalf': 0,
    'bpmIntro': 0
  },
};
